name: Generate snake game

on:
  schedule:
    - cron: '0 */12 * * *'  # This will run the workflow every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Update snake animation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: ephy-bayru/snake-game@master
        with:
          github_user_name: ephy-bayru
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue' # You can choose any color you prefer

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
